version: "3.3"
services:
  gin_pgsql:
    image: postgres:14
    container_name: gin_pgsql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db_testing
    logging:
      driver: none
  gin_redis:
    image: redis:latest
    container_name: gin_redis
    ports:
      - 6379:6379
    logging:
      driver: none
  gin_jaeger:
    image: jaegertracing/all-in-one:1.29
    container_name: gin_jaeger
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    logging:
      driver: none